# Generated by Django 3.1.3 on 2020-12-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0003_auto_20201211_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Sd card availability'),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='sd_max_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Max Sd capacity'),
        ),
    ]
