# Generated by Django 3.1.3 on 2020-12-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0004_auto_20201215_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Final Price'),
        ),
    ]
