# Generated by Django 3.1.3 on 2020-12-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0006_auto_20201222_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
