# Generated by Django 3.1.3 on 2020-12-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0008_auto_20201224_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oneapp.cart', verbose_name='Basket'),
        ),
    ]
